version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    groups:
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
      vitest:
        patterns:
          - '@vitest/*'
          - 'vitest'
      react:
        patterns:
          - 'react'
          - 'react-dom'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
